### ISSUE TITLE
Profile Picture Not Showing

### ISSUE THREAD

**Issue by dzakisulthann** [saeedvaziry/ibio#13]
Hello,

First of all, thank you so much for this code.

Im facing a little problem here. Profile picture not showing after i save and refresh the page. It's not showing either on the profile section or on my page section. Whe i refresh the page after saving my profile picture, it just showing my username. I have asked my friend to install this code on their computer and we all facing the same problem. This problem happens on localhost and on my website. Maybe if you want to check it directly you can go to my web sudutbkt.com, but i also attached some screenshot.

![image](https://user-images.githubusercontent.com/127910460/225193701-c4f0e33c-6b34-4cdd-9507-fc2d8e3a93d3.png)
![image](https://user-images.githubusercontent.com/127910460/225193807-e552f1ad-1d68-442f-b590-5e1a50566ee5.png)

Thank you so much, hope you can help me.

**Comment by saeedvaziry** [comment]
You need to link your storage to public folder.

```
php artisan storage:link
```
