### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by abbasudo** [saeedvaziry/ibio#7]
hi . thanks for your hard work and your support to open source community
im a noob laravel developer and I want to contribute to this project . Please add a simple installation guide and fill the env.example . thanks

**Comment by saeedvaziry** [comment]
@llabbasmkhll Thanks for considering to contribute. 
This is a simple Laravel project and has a normal installation like all Laravel projects. However, I updated the Readme file and added an installation section.
