### ISSUE TITLE
RuntimeException The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. 

### ISSUE THREAD

**Issue by sadi-abasi** [saeedvaziry/ibio#8]
hi. so i was trying to setup the applation as a side bonus for our website i just keep bumping into new issues well mainly becuase i didn't even know that laravel existed until i look into how i can use this program and at frist i had problem with it not finding the js scripe file's that i fixed in the must jank way possible and now this i scaterd the internet coulden't find anything that work like ` php artisan key:generate` or deleting the env form app config. so i was hopeing you could help me solve the issue?!

**Comment by saeedvaziry** [comment]
@TheDarkStone This issue has been resolved in the master branch.
please fetch the latest updates from the master branch.
